osx_image: xcode9.2
language: swift

script:
  - xcodebuild -scheme TodoSample -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.2,name=iPhone X' -configuration Debug test | xcpretty -c
